name: Deploy to nhcuong.cloud

on:
  push:
    branches: ["dev-me"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - id: nvmrc
      uses: browniebroke/read-nvmrc-action@v1

    - name: Use Node.js from nvmrc
      uses: actions/setup-node@v6
      with:
        node-version: '${{ steps.nvmrc.outputs.node_version }}'
        cache: 'npm'

    - name: Instal gatsby
      run: npm install -g gatsby-cli

    - name: Install dependencies
      run: yarn

    - name: Extend node memory
      run: export NODE_OPTIONS="--max-old-space-size=8192"

    - name: Build application
      run: yarn build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-files
        path: public/
        retention-days: 1

  deploy-develop:
    needs: build
    runs-on: ubuntu-latest
    environment: staging
    # if: github.ref == 'refs/heads/develop'

    env:
      DEPLOY_DIR: /var/www/portfolio

    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: dist-files
        path: public/

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy application
      run: |
        # Create deployment directory and deploy files
        ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "mkdir -p ${{ env.DEPLOY_DIR }}"
        scp -i ~/.ssh/id_rsa -r ./dist/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ env.DEPLOY_DIR }}/


    - name: Reload nginx server
      run: ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "sudo nginx -s reload"

    - name: Cleanup SSH
      if: always()
      run: rm -f ~/.ssh/id_rsa
